byte layout[NUM_LAYOUT_LEVELS][NUM_ROWS][NUM_COLS] = {
  {
    {K_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, K_BKS},
    {K_ESC, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, K_SCL, K_ETR},
    {K_S_L, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, K_EQU, K_CMA, K_DOT, K_S_R},
    {K_C_L, K_G_L, K_A_L, HIGHR, K_SPC, K_OSB, K_CSB, K_MIN, K_SPC, K_SQO, K_FSL, K_BSL}
  },
  {
    {K_OSB, K_CSB, K_DEL, K_HOM, K_END, K_PUP, K_PDN, KEY_7, KEY_8, KEY_9, K_BSL, K_BKS},
    {K_ESC, K_BTK, K_F04, K_F05, K_F06, K_INS, K_NON, KEY_4, KEY_5, KEY_6, K_EQU, K_ETR},
    {K_S_L, K_NON, K_NON, K_NON, BATLV, K_NON, K_NON, KEY_1, KEY_2, KEY_3, K_AUP, K_S_R},
    {K_C_L, K_NON, K_G_L, HIGHR, K_NON, K_SPC, CTALD, K_CPS, KEY_0, K_LFT, K_DWN, K_RHT}
  }
};
